language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - TF=1.12
  - TF=1.13
  - TF=1.14
  - TF=1.15
  - TF=2.0
  - TF=2.1
  - TF=2.2

install:
  - pip install pytest_mock
  - pip install pytest_cov
  - pip install codecov 
  - pip install numpy
  - pip install tensorflow==$TF
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python setup.py install

script:
  - pytest --cov-report=xml --cov=psychrnn/ 

after_success:
  - codecov
